// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package upstream

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpstreamInit-1]
	_ = x[UpstreamWorking-2]
	_ = x[UpstreamPaused-3]
	_ = x[UpstreamUnavailable-4]
	_ = x[UpstreamStopping-5]
	_ = x[UpstreamStopped-6]
	_ = x[UpstreamRemoving-7]
	_ = x[UpstreamRemoved-8]
}

const _Status_name = "initworkingpausedunavailablestoppingstoppedremovingremoved"

var _Status_index = [...]uint8{0, 4, 11, 17, 28, 36, 43, 51, 58}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
