// Code generated by "stringer -type=UpstreamStatus -linecomment"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpstreamInit-1]
	_ = x[UpstreamWorking-2]
	_ = x[UpstreamPaused-3]
	_ = x[UpstreamUnavailable-4]
	_ = x[UpstreamStopping-5]
	_ = x[UpstreamStopped-6]
	_ = x[UpstreamRemoving-7]
	_ = x[UpstreamRemoved-8]
}

const _UpstreamStatus_name = "initworkingpausedunavailablestoppingstoppedremovingremoved"

var _UpstreamStatus_index = [...]uint8{0, 4, 11, 17, 28, 36, 43, 51, 58}

func (i UpstreamStatus) String() string {
	i -= 1
	if i < 0 || i >= UpstreamStatus(len(_UpstreamStatus_index)-1) {
		return "UpstreamStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UpstreamStatus_name[_UpstreamStatus_index[i]:_UpstreamStatus_index[i+1]]
}
